### ISSUE TITLE
Combined Doses 7 day average

### ISSUE THREAD

**Issue by SamAsh91** [nicjac/vaccine-tracker-uk#10]
I think the daily and weekly change values on the for the 7 day average, first + second doses seem far too high (unless I'm misunderstanding something?). Percentage changes seem to be correct though.

**Comment by nicjac** [comment]
@SamAsh91 I can't believe I never noticed this! Thanks for the heads-up, should now be fixed.

**Comment by SamAsh91** [comment]
Do you know what it was actually calculating? I tried to work it out, but didn't really get anywhere
