### ISSUE TITLE
Remove www sub domain

### ISSUE THREAD

**Issue by james090500** [nicjac/vaccine-tracker-uk#4]
This has happened 3 times for me now. I send the website to someone or visit it on a new device and it fails because I have missed the www. subdomain

**Doesn't load**: https://vaccine-tracker.uk/ 
**Loads**: https://www.vaccine-tracker.uk/

**Comment by nicjac** [comment]
Dealing with custom domain / https issues with Github Pages has been the bane of my life. The current setup is the only one that worked - if I were to set the custom domain to the apex, the www subdomain stops working altogether.

One thing I could try is set the custom domain to the apex, and use an alias domain to redirect www to said apex.

**Comment by harad** [comment]
@nicjac, have you tried the below approach? 
[https://stackoverflow.com/questions/59596179/github-pages-redirect-non-www-root-domain-to-www-subdomain](https://stackoverflow.com/questions/59596179/github-pages-redirect-non-www-root-domain-to-www-subdomain)

**Comment by nicjac** [comment]
> @nicjac, have you tried the below approach?
> https://stackoverflow.com/questions/59596179/github-pages-redirect-non-www-root-domain-to-www-subdomain

I've tried this a while ago and it resulted in similar certificate issues. Will give it another shot. Thanks!

**Comment by Ollie1700** [comment]
I stumbled across this project on Google looking for estimates for when my wife and I might be able to get the first dose - we'd like to thank you for your hard work on this great resource!

If you're still having issues with this (and if it's a big enough deal to warrant dealing with it) I'd be more than happy to help you host the site with correct SSLs for www/non-www? Let me know if it's of use at all!

**Comment by nicjac** [comment]
> I stumbled across this project on Google looking for estimates for when my wife and I might be able to get the first dose - we'd like to thank you for your hard work on this great resource!
> 
> If you're still having issues with this (and if it's a big enough deal to warrant dealing with it) I'd be more than happy to help you host the site with correct SSLs for www/non-www? Let me know if it's of use at all!

I've been trying to deal with it since this issue was first created - it's driving me nuts, and Github support basically told me having SSL for both the root domain and a www subdomain at the same time is not supported.

Thank you for your kind hosting offer. Ideally I would find a way to deal with the whole DNS / SSL thing without having to leave Github pages (due to the CI/CD integration for automated updates based on data release by PHE).

**Comment by Ollie1700** [comment]
> without having to leave Github pages (due to the CI/CD integration for automated updates based on data release by PHE).

Ah I see - of course, no problem! Please feel free to reach out in the future if you think I can be of assistance!

**Comment by james090500** [comment]
Closing as this seems mostly fixed
